### PR TITLE
change threshold for signature accuracy

### PR DESCRIPTION
**Pull request by oscar-davids**
changed threshold to increase Mpeg-7 signature accuracy.

### CODE REVIEW

**Review by thomshutt — APPROVED** [review]
Not sure how meaningfully I can review this, but the new numbers look great and the old ones look terrible 😄

**Comment by yondonfu** [comment]
@oscar-davids Can you explain what the impact of changing the fields in the `SignatureContext` in this PR is?

I understand that the new values for these fields result in higher accuracy in our benchmark tests for signature comparison. However, if these fields change the threshold at which a two signatures are considered a match, does this mean this PR lowers the threshold allowing more signature pairs to be considered a match? If this is the case, does this allow more invalid signature pairs to be misclassified as a match? I assume there is some tradeoff there is made by changing the threshold here and I think it would be useful to make sure we understand what that tradeoff is.

**Comment by oscar-davids** [comment]
@yondonfu You are right.
The accuracy increases by 1%, while the false accept rate increases by 0.3% for signature comparison.
All video segments from Ts are short and even have a sentinel frame. For these few-video-frame segments, mpeg-7 signature filter doesn't work well. It would be nice to modify the signature comparison part, but since there would be a lot of effort at the moment, I decided on the threshold through experiments and analysis of the source.

**Comment by yondonfu** [comment]
Thanks for the explanation. For the future, would be great to see a repeatable benchmark test included in this repo that anyone could run on a standard dataset to observe how changes to the `SignatureContext` fields update the accuracy, false positive, etc. rates.

**Pull request merged**
